[package]
name = "print_text_slow"
version = "0.1.0"
authors = ["BlauskaerM <blauskaerm@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
ansi_term = "0.12"
clap = "2.33.3"
